// Auto-generated by The Agency orchestrator.
window.ENV = window.ENV || {};
window.ENV.SUPABASE_URL = "https://saovircuzswtespcghij.supabase.co";
window.ENV.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhb3ZpcmN1enN3dGVzcGNnaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzNTA2ODAsImV4cCI6MjA5NTkyNjY4MH0.1Q-3Eo_VKmgENrM1w95WNUNw4Yq9TV2247tUEcm78n8";
